/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DatasetIdRouteImport } from './routes/dataset.$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTokensRouteImport } from './routes/admin/tokens'
import { Route as AdminRepositoriesRouteImport } from './routes/admin/repositories'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminInfrastructureRouteImport } from './routes/admin/infrastructure'
import { Route as AdminHelpDeskRouteImport } from './routes/admin/help-desk'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminAssistantRouteImport } from './routes/admin/assistant'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminAgentsRouteImport } from './routes/admin/agents'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DatasetIdRoute = DatasetIdRouteImport.update({
  id: '/dataset/$id',
  path: '/dataset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTokensRoute = AdminTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRepositoriesRoute = AdminRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInfrastructureRoute = AdminInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHelpDeskRoute = AdminHelpDeskRouteImport.update({
  id: '/help-desk',
  path: '/help-desk',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssistantRoute = AdminAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/help': typeof AuthenticatedHelpRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/help-desk': typeof AdminHelpDeskRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/repositories': typeof AdminRepositoriesRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dataset/$id': typeof DatasetIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/help': typeof AuthenticatedHelpRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/help-desk': typeof AdminHelpDeskRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/repositories': typeof AdminRepositoriesRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dataset/$id': typeof DatasetIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/help-desk': typeof AdminHelpDeskRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/repositories': typeof AdminRepositoriesRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dataset/$id': typeof DatasetIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/search'
    | '/help'
    | '/history'
    | '/onboarding'
    | '/saved'
    | '/settings'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/assistant'
    | '/admin/audit-log'
    | '/admin/help-desk'
    | '/admin/infrastructure'
    | '/admin/moderation'
    | '/admin/repositories'
    | '/admin/tokens'  | '/admin/settings'
  | '/admin/users'
  | '/dataset/$id'
  | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/settings'
    | '/'
    | '/auth'
    | '/search'
    | '/help'
    | '/history'
    | '/onboarding'
    | '/saved'
    | '/settings'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/assistant'
    | '/admin/audit-log'
    | '/admin/help-desk'
    | '/admin/infrastructure'
    | '/admin/moderation'
    | '/admin/repositories'
    | '/admin/tokens'
    | '/admin/settings'
    | '/admin/users'
    | '/dataset/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/search'
    | '/_authenticated/help'
    | '/_authenticated/history'
    | '/_authenticated/onboarding'
    | '/_authenticated/saved'
    | '/_authenticated/settings'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/assistant'
    | '/admin/audit-log'
    | '/admin/help-desk'
    | '/admin/infrastructure'
    | '/admin/moderation'
    | '/admin/repositories'    | '/admin/tokens'
    | '/admin/settings'
    | '/admin/users'
    | '/dataset/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  DatasetIdRoute: typeof DatasetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dataset/$id': {
      id: '/dataset/$id'
      path: '/dataset/$id'
      fullPath: '/dataset/$id'
      preLoaderRoute: typeof DatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tokens': {
      id: '/admin/tokens'
      path: '/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AdminTokensRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/repositories': {
      id: '/admin/repositories'
      path: '/repositories'
      fullPath: '/admin/repositories'
      preLoaderRoute: typeof AdminRepositoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/infrastructure': {
      id: '/admin/infrastructure'
      path: '/infrastructure'
      fullPath: '/admin/infrastructure'
      preLoaderRoute: typeof AdminInfrastructureRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/help-desk': {
      id: '/admin/help-desk'
      path: '/help-desk'
      fullPath: '/admin/help-desk'
      preLoaderRoute: typeof AdminHelpDeskRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/assistant': {
      id: '/admin/assistant'
      path: '/assistant'
      fullPath: '/admin/assistant'
      preLoaderRoute: typeof AdminAssistantRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAssistantRoute: typeof AdminAssistantRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminHelpDeskRoute: typeof AdminHelpDeskRoute
  AdminInfrastructureRoute: typeof AdminInfrastructureRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminRepositoriesRoute: typeof AdminRepositoriesRoute
  AdminTokensRoute: typeof AdminTokensRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAssistantRoute: AdminAssistantRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminHelpDeskRoute: AdminHelpDeskRoute,
  AdminInfrastructureRoute: AdminInfrastructureRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminRepositoriesRoute: AdminRepositoriesRoute,
  AdminTokensRoute: AdminTokensRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  DatasetIdRoute: DatasetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
